[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''self.GAME.selected_back_key = selected_back'''
payload = '''
init_perkeocoin(self.GAME)
'''
match_indent = true

# Custom Font for attention_text()
[[patches]]
[patches.regex]
target = 'functions/UI_definitions.lua'
position = 'after'
pattern = '''colours = \{args\.colour\}\,float = true\,'''
payload = '''font = args.font,'''

# make the czech colour
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
position = 'after'
pattern = '''spectral = G.C.SECONDARY_SET.Spectral,'''
payload = '''hpot_czech = HEX("D2B48C"),'''
match_indent = true
